kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "ansible_rfe_build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/andrewWithTheRedhat/ansible/rfe/buildConfigs"
      ref: main
    contextDir: /
  strategy:
  dockerStrategy:
    dockerfilePath: Dockerfile
  output: 
    to:
      kind: "ImageStreamTag"
      name: "ansible_rfe:latest"
