kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: rfe-ansible
  selfLink: /apis/project.openshift.io/v1/projects/rfe-ansible
  uid: 5b3993a4-03ca-43b1-8349-38e0d37bc7d2
  resourceVersion: '3256164'
  creationTimestamp: '2021-02-24T22:32:11Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ansible rfe container
    openshift.io/requester: andrewWithTheRedHat
    openshift.io/sa.scc.mcs: 's0:c26,c15'
    openshift.io/sa.scc.supplemental-groups: 1000680000/10000
    openshift.io/sa.scc.uid-range: 1000680000/10000
  managedFields:
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2021-02-24T22:32:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2021-02-24T22:32:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
        'f:status':
          'f:phase': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-02-24T22:32:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
