kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "ansible-rfe-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/andrewWithTheRedhat/ansible-rfe-buildConfigs"
      ref: main
    images:
    - from:
        kind: ImageStreamTag
        name: ansible-rfe-build:latest
        namespace: rfe-ansible
    contextDir: /
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
