kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "ansible-rfe-build" 
spec:
  runPolicy: "Serial" 
  source:
  git:
    uri: https://github.com/andrewWithTheRedHat/ansible-rfe-buildConfigs.git"
  contextDir: \ 
  dockerfile: "FROM registry.access.redhat.com/ubi8/python-38\USER 0\RUN dnf update -y\RUN pip install --upgrade pip\RUN pip install openshift\RUN pip install ansible==2.9.*\USER 1001"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "ansible-rfe-build:latest"
